### ISSUE TITLE
Mouse look not working?

### ISSUE THREAD

**Issue by speharas** [kzahel/WebQuake-Chrome#2]
The previous version allowed mouse look, but for some reason now it doesn't.

**Comment by kzahel** [comment]
press ~ key and type +mlook?

**Comment by speharas** [comment]
Didn't work.

**Comment by kzahel** [comment]
you have to start the game first to open the console (with tilde button,
left of 1 key). did you see the console?

**Comment by kzahel** [comment]
Oh, I see. pointerLock is not even working. Let me look into it. Thanks for
letting me know

**Comment by speharas** [comment]
No worries :)

**Comment by ghost** [comment]
I'm using Chrome 39 on Windows 7 and mouse look is not working. "PointerLock" functions are null which is weird since pointerLock works on other pages.

**Comment by remife** [comment]
any update on pointerlock not working?

**Comment by kzahel** [comment]
I fixed it. Sorry about taking a year to do it :-)

**Comment by speharas** [comment]
Haha, all good. Thank you!

On 4 May 2016 at 03:20, Kyle Graehl notifications@github.com wrote:

> I fixed it. Sorry about taking a year to do it :-)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/kzahel/WebQuake-Chrome/issues/2#issuecomment-216601812

## 

_AS_
