### ISSUE TITLE
Not Saving Between Reboots

### ISSUE THREAD

**Issue by nivekregrub** [kzahel/WebQuake-Chrome#3]
I have an HP Chromebook 14 and am running the most recent version of Web Quake from the Chrome Web Store. I can save and load games, but when I reboot my computer all of the saved games are lost. Relevant computer info follows. The only thing I've done to it is to switch to developer mode.

HP Chromebook 14
Chrome Version 43.0.2357.81 (64-bit build)
Platform 6946.55.0 (Official build) stable-channel falco
Firmware Google_Falco.4389.92.0
Webkit 537.36 (@195776)
V8 4.3.61.23
User Agent
Mozilla/5.0 (X11; CrOS x86_64 6946.55.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36

Command Line
/opt/google/chrome/chrome --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=17.0.0.188-r1 --ppapi-flash-args=enable_hw_video_decode=1 --enable-fixed-position-compositing --enable-impl-side-painting --max-tiles-for-interest-area=512 --ui-enable-per-tile-painting --ui-prioritize-in-gpu-process --use-gl=egl --gpu-sandbox-failures-fatal=yes --ozone-platform=gbm --ozone-use-surfaceless --enable-logging --log-level=1 --use-cras --user-data-dir=/home/chronos --max-unused-resource-memory-usage-percentage=5 --system-developer-mode --login-profile=user --has-chromeos-keyboard --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/oem_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/oem_small.jpg --default-wallpaper-is-oem --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --enterprise-enable-forced-re-enrollment --enterprise-enrollment-initial-modulus=13 --enterprise-enrollment-modulus-limit=17 --vmodule=screen_locker=1,webui_screen_locker=1,_ui/display/chromeos_=1,_ash/display_=1,_ui/ozone_=1,_zygote_=1,_plugin_=2 --login-manager --first-exec-after-boot --ozone-use-surfaceless

The device is Up To Date.

**Comment by kzahel** [comment]
Thanks I have been getting several reports of this. I also have been getting reports that mouse movement is not working (simple fix) I will try to look into these two problems this week!

**Comment by hunterhuntedcrow** [comment]
same trouble, except it seems as though when I reboot, the functions of crosh, dash, do not work, so I am unable to fix the problems, any suggestions?
/opt/google/chrome/chrome --enable-logging --gpu-sandbox-failures-fatal=yes --ppapi-flash-args=enable_hw_video_decode=1 --ppapi-flash-path=/opt/google/chrome/pepper/libpepflashplayer.so --ppapi-flash-version=18.0.0.209-r1 --ui-prioritize-in-gpu-process --use-cras --use-gl=egl --user-data-dir=/home/chronos --vmodule=screen_locker=1,webui_screen_locker=1,_ui/display/chromeos_=1,_ash/display_=1,_ui/ozone_=1,_zygote_=1,_plugin_=2 --ozone-platform=gbm --ozone-use-surfaceless --default-wallpaper-large=/usr/share/chromeos-assets/wallpaper/oem_large.jpg --default-wallpaper-small=/usr/share/chromeos-assets/wallpaper/oem_small.jpg --guest-wallpaper-large=/usr/share/chromeos-assets/wallpaper/guest_large.jpg --guest-wallpaper-small=/usr/share/chromeos-assets/wallpaper/guest_small.jpg --max-tiles-for-interest-area=512 --max-unused-resource-memory-usage-percentage=5 --has-chromeos-keyboard --login-profile=user --bwsi --homepage=chrome://newtab/ --incognito --log-level=1 --login-user=$guest --login-user=$guest --login-profile=8b8993b50eae845eb7cb29116bc53a597d8f25b8 --disable-sync --disable-extensions --ozone-use-surfaceless
Build Date

**Comment by hunterhuntedcrow** [comment]
Using an Acer Chromebook 11, build date was July 25, 2015 and seems to occur after an "automatic" update. 
Thanks new to this

**Comment by kzahel** [comment]
Sorry I haven't had time to look into this.

**Comment by madddmike** [comment]
Seeing the same thing on Lenovo Thinkpad W540.  Games won't save between reboots.

**Comment by kzahel** [comment]
You have to quit through the menu.
I made it just save the config any time you enter/exit the menu so should fix it.
