### ISSUE TITLE
Multiplayer URLs not displaying

### ISSUE THREAD

**Issue by kutzk1** [kzahel/WebQuake-Chrome#7]
When I try to launch a multiplayer server, it doesn't give me any URLs at the bottom for other people to connect. I've tried Quake commands and everything else I could think of to try to get it to show the address, but nothing worked. I'm using an Acer R 11 Chromebook.

**Comment by kzahel** [comment]
Stable channel? Beta channel? Dev channel?

**Comment by kutzk1** [comment]
What do you mean?

Edit: Oh, it's stable channel.

**Comment by kzahel** [comment]
I'm guessing stable channel if you don't know. One thing you could do is open a tab and type into the url chrome://inspect and look for app pages and background pages that say webquake, and then in the window that appears, click on console. Then try to start a multiplayer server. And then see if there are new windows in chrome://inspect appearing. And see if there is any text (especially red text) in the window, that would help me figure out what's really going on.

**Comment by kutzk1** [comment]
When I launch Web Quake, it appears in the apps section as /launch.html and in the extensions section as /_generated_background_page.html
After clicking "Start Multiplayer Server", another instance of Web Quake labeled as server/server.html? appears in the apps section.
I'm not sure what all is important in the Server window, so here's all the text it displays when starting up:

Host.Init
Added packfile id1/pak0.pak (339 files)
FindFile: id1/gfx/pop.lmp
Playing registered version.
PackFile: id1/pak0.pak : gfx/palette.lmp
========Quake Initialized=========
PackFile: id1/pak0.pak : quake.rc
execing quake.rc
PackFile: id1/pak0.pak : default.cfg
execing default.cfg
Unknown command "unbindall"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "bind"
Unknown command "viewsize"
Unknown command "gamma"
Unknown command "volume"
Unknown command "sensitivity"
FindFile: id1/config.cfg
execing config.cfg
FindFile: can't find autoexec.cfg
couldn't exec autoexec.cfg
PackFile: id1/pak0.pak : progs.dat
PackFile: id1/pak0.pak : maps/start.bsp
PackFile: id1/pak0.pak : progs/player.mdl
PackFile: id1/pak0.pak : progs/eyes.mdl
PackFile: id1/pak0.pak : progs/h_player.mdl
PackFile: id1/pak0.pak : progs/gib1.mdl
PackFile: id1/pak0.pak : progs/gib2.mdl
PackFile: id1/pak0.pak : progs/gib3.mdl
PackFile: id1/pak0.pak : progs/s_bubble.spr
PackFile: id1/pak0.pak : progs/s_explod.spr
PackFile: id1/pak0.pak : progs/v_axe.mdl
PackFile: id1/pak0.pak : progs/v_shot.mdl
PackFile: id1/pak0.pak : progs/v_nail.mdl
PackFile: id1/pak0.pak : progs/v_rock.mdl
PackFile: id1/pak0.pak : progs/v_shot2.mdl
PackFile: id1/pak0.pak : progs/v_nail2.mdl
PackFile: id1/pak0.pak : progs/v_rock2.mdl
PackFile: id1/pak0.pak : progs/bolt.mdl
PackFile: id1/pak0.pak : progs/bolt2.mdl
PackFile: id1/pak0.pak : progs/bolt3.mdl
PackFile: id1/pak0.pak : progs/lavaball.mdl
PackFile: id1/pak0.pak : progs/missile.mdl
PackFile: id1/pak0.pak : progs/grenade.mdl
PackFile: id1/pak0.pak : progs/spike.mdl
PackFile: id1/pak0.pak : progs/s_spike.mdl
PackFile: id1/pak0.pak : progs/backpack.mdl
PackFile: id1/pak0.pak : progs/zom_gib.mdl
PackFile: id1/pak0.pak : progs/v_light.mdl
PackFile: id1/pak0.pak : progs/flame2.mdl
PackFile: id1/pak0.pak : progs/flame.mdl
PackFile: id1/pak0.pak : progs/zombie.mdl
PackFile: id1/pak0.pak : progs/h_zombie.mdl

**Comment by kzahel** [comment]
Yeah that information you posted is not useful. Inspect the server page and go to console
![capture](https://cloud.githubusercontent.com/assets/158352/19622234/f180cea8-9859-11e6-9b0d-5e44834f6482.PNG)

**Comment by kutzk1** [comment]
Clicking Inspect doesn't do anything.
Edit: I don't think I have Admin permissions. Do I need that to do this?

**Comment by kzahel** [comment]
![captur2e](https://cloud.githubusercontent.com/assets/158352/19622260/a4de8e4a-985a-11e6-917f-92cc9aa5c6f0.PNG)

**Comment by kzahel** [comment]
no window pops up when you click on Inspect under the server.html app page?

**Comment by kutzk1** [comment]
No, nothing pops up when I click Inspect.

**Comment by kutzk1** [comment]
Do I need Admin permissions to do that?

**Comment by kutzk1** [comment]
It looks like the admins disabled the inspect element option on our chromebooks.

**Comment by kutzk1** [comment]
I just logged in on a personal computer, and I am now able to inspect the app.
What exactly am I looking for?

**Comment by kutzk1** [comment]
![screen shot 2016-10-22 at 3 40 01 pm](https://cloud.githubusercontent.com/assets/23003635/19622366/de651dec-986d-11e6-86fc-f5a1ebef0a12.png)

**Comment by kutzk1** [comment]
I figured out how to inspect it, finally. These were the only errors listed in the console.

**Comment by kutzk1** [comment]
Are there any settings I can change to make this work, or is this a problem inherent in the app?

**Comment by kzahel** [comment]
It's a problem with my code.

**Comment by kutzk1** [comment]
Alright. Well, I hope this helps you, and I look forward to a future fix.

**Comment by kzahel** [comment]
Thanks! That helps I'll try and fix it soon.

**Comment by kzahel** [comment]
Give it another try. You can get the app to update by going to chrome://extensions and clicking on developer mode and then "Update extensions now". You should see version 1.0.5
Or it should auto update itself in a day or so.

**Comment by kzahel** [comment]
So it works now?

**Comment by kutzk1** [comment]
It seems so. The IP addresses display fine now, and I can connect to the server hosted on my 'Book, but I haven't had a chance to test connecting from a second computer yet. I'll test that later today.

**Comment by kutzk1** [comment]
I just tested it with a friend. We both could connect just fine. Thanks so much for fixing this bug, and for making this app.

**Comment by kzahel** [comment]
Great! Thanks for reporting the bug and helping me find out what went wrong. I'm sure the same problem was affecting others, so they should thank you too :-)
